version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: TranslatorDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: parallel_translator
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TranslatorDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
